### ISSUE TITLE
Wasp Catchup

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/docs.iota.org#46]
- [x] Review all the installation instructions are present and up to date.
- [ ] Review all types, returns, etc in provided examples.
- [ ] Wrap examples in user stories.  
- [ ] Add a cheat sheet. [Brainstorm Doc](https://hackmd.io/@WZdHn6o0TmiYck3zlENRsw/SyKRAGkNt/edit)

**Comment by huhn511** [comment]
## Wiki series
- [ ] Smart Contract VM & Language
- [ ] Validators
- [ ] Smart Contract Chains
- [ ] dApps & User interactions
- [ ] Consensus
- [ ] IOTA Tangle
